### ISSUE TITLE
docker install failed

### ISSUE THREAD

**Issue by whiplashen** [sunshine2077/WSL2-Help#1]
Problem：
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo service docker start
And get the output: docker is not running
Reason: Don't have a deamon service
Try:
1.Update the wsl :
wsl update
2.Set the version of wsl:
wsl --set-version Ubuntu 2
3.Ubuntu:
sudo systemctl  start docker 
SUCCESS!
You can update the file by my exercise.

**Comment by sunshine2077** [comment]
Year, only WSL2 has the daemon. This issue is useful.
